version: '2'
services:
  jenkins_master:
    build: ./jenkins_master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                                                                                                                               
      - /var/lib/docker:/var/lib/docker
      - $SSH_AUTH_SOCK:/ssh-agent 

    environment:
      SSH_AUTH_SOCK: /ssh-agent
  jenkins_slave:
    build: ./jenkins_slave  
    links: 
      - jenkins_master
    depends_on:
      - jenkins_master
  
